FLAG=-std=c++11 -lpthread -I ~/bit/oj/minigoogle/cppjieba/include/
search_http:search_http.cc  ../search/libsearcher.so 
	g++ search_http.cc  ../search/libsearcher.so -o search_http $(FLAG) -lboost_filesystem -lboost_system
